name: Workflow Call Test

on:
  push:

jobs:

  build-custom:
    uses: stellar/quickstart/.github/workflows/build.yml@65011f6e4e83e0ed23274e60f8b4b74ec9ca656f
    with:
      ref: 65011f6e4e83e0ed23274e60f8b4b74ec9ca656f
      images: |
        [
          {
            "tag": "custom",
            "config": {
              "protocol_version_default": 23
            },
            "deps": [
              { "name": "xdr", "repo": "stellar/rs-stellar-xdr", "ref": "v23.0.0" },
              { "name": "core", "repo": "stellar/stellar-core", "ref": "v23.0.1", "options": { "configure_flags": "--disable-tests" } },
              { "name": "rpc", "repo": "stellar/stellar-rpc", "ref": "v23.0.1" },
              { "name": "horizon", "repo": "stellar/go", "ref": "horizon-v23.0.0" },
              { "name": "friendbot", "repo": "stellar/go", "ref": "horizon-v23.0.0" },
              { "name": "lab", "repo": "stellar/laboratory", "ref": "main" }
            ],
            "additional-tests": []
          }
        ]
      archs: '["amd64"]'

  use-custom:
    needs: build-custom
    runs-on: ubuntu-latest
    steps:
    - uses: stellar/quickstart@65011f6e4e83e0ed23274e60f8b4b74ec9ca656f
      with:
        artifact: image-quickstart-custom-amd64.tar
        tag: custom-amd64
    - run: sleep 10
    - run: curl http://localhost:8000
